batch_size: 512
learning_rate: 0.01
n_layers: 5
hidden_width: 64
epochs: 5
seed: 1234
last_hidden_width: 512

device: cuda
model: resnet-conv
atype: relu
data_code: mnist
model_file: hsic_weight_resconv_mnist.pt
task: resconv
training_type: backprop

log_batch_interval: 2
verbose: 0
ext: pdf
exp_index: null

