batch_size: 256 # for hsic-training, task.task_variedep determines format-trainin batchsize
learning_rate: 0.0001
sigma: 5.
lambda_x: 1.
lambda_y: 50.
epochs: 1 # determined by script
n_layers: 5
hidden_width: 256
last_hidden_width: 128
seed: 1234

device: cuda
model: linear
atype: relu
data_code: mnist
model_file: hsic_weight_varied_epoch_mnist.pt # will be modified by task.task_variedep
checkpoint: null
training_type: hsictrain
task: varied-epoch

verbose: 0
log_batch_interval: 20
exp_index: 0 # determined by task.task_variedep
